import { mysqlTable, mysqlSchema, AnyMySqlColumn, unique, varchar, timestamp, varbinary, float, datetime, longtext, text, int, bigint } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"


export const BachBaoCacRecord = mysqlTable("BachBaoCacRecord", {
	ID: int("ID").autoincrement().notNull(),
	UserId: varchar("UserId", { length: 50 }),
	UserName: varchar("UserName", { length: 50 }),
	VatPham_ID: varchar("VatPham_ID", { length: 50 }),
	VatPhamTen: varchar("VatPhamTen", { length: 50 }),
	VatPhamSoLuong: int("VatPhamSoLuong"),
	NguyenBaoSoLuong: int("NguyenBaoSoLuong"),
	ThoiGian: timestamp("ThoiGian", { mode: 'string' }),
},
(table) => {
	return {
		ID: unique("ID").on(table.ID),
	}
});

export const Character = mysqlTable("Character", {
	ID: int("ID").notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }).notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_INDEX: int("FLD_INDEX").notNull(),
	FLD_LEVEL: int("FLD_LEVEL"),
	FLD_FACE: varbinary("FLD_FACE", { length: 10 }),
	FLD_JOB: int("FLD_JOB").notNull(),
	FLD_EXP: varchar("FLD_EXP", { length: 50 }),
	FLD_ZX: int("FLD_ZX"),
	FLD_JOB_LEVEL: int("FLD_JOB_LEVEL"),
	FLD_X: float("FLD_X"),
	FLD_Y: float("FLD_Y"),
	FLD_Z: float("FLD_Z"),
	FLD_MENOW: int("FLD_MENOW"),
	FLD_MONEY: varchar("FLD_MONEY", { length: 50 }),
	FLD_MoneyX: varchar("FLD_MoneyX", { length: 50 }),
	FLD_HP: int("FLD_HP"),
	FLD_MP: int("FLD_MP"),
	FLD_SP: int("FLD_SP"),
	FLD_WX: int("FLD_WX"),
	FLD_SE: int("FLD_SE"),
	FLD_POINT: int("FLD_POINT"),
	FLD_SKILLS: varbinary("FLD_SKILLS", { length: 100 }),
	FLD_WEARITEM: varbinary("FLD_WEARITEM", { length: 5000 }),
	FLD_WEARITEMFZ: varbinary("FLD_WEARITEMFZ", { length: 1500 }),
	FLD_LCWEARITEM: varbinary("FLD_LCWEARITEM", { length: 73 }),
	FLD_ITEM: varbinary("FLD_ITEM", { length: 8000 }),
	FLD_ItemNTC: varbinary("FLD_ItemNTC", { length: 438 }),
	FLD_QITEM: varbinary("FLD_QITEM", { length: 300 }),
	FLD_KONGFU: varbinary("FLD_KONGFU", { length: 1404 }),
	FLD_HITS: varbinary("FLD_HITS", { length: 250 }),
	FLD_DOORS: varbinary("FLD_DOORS", { length: 1200 }),
	FLD_QUEST: varbinary("FLD_QUEST", { length: 400 }),
	FLD_LUMPID: int("FLD_LUMPID"),
	FLD_CTIME: varbinary("FLD_CTIME", { length: 320 }),
	FLD_FIGHT_EXP: int("FLD_FIGHT_EXP"),
	FLD_J9: int("FLD_J9"),
	FLD_JQ: int("FLD_JQ"),
	FLD_JL: varchar("FLD_JL", { length: 50 }),
	FLD_NAMETYPE: varbinary("FLD_NAMETYPE", { length: 48 }),
	FLD_ZBVER: int("FLD_ZBVER"),
	FLD_ZzType: int("FLD_ZzType"),
	FLD_ZzSl: int("FLD_ZzSl"),
	FLD_CTIMENEW: varbinary("FLD_CTIMENEW", { length: 240 }),
	FLD_QlNAME: varchar("FLD_QlNAME", { length: 50 }),
	FLD_QlJZNAME: varchar("FLD_QlJZNAME", { length: 50 }),
	FLD_QlDu: int("FLD_QlDu"),
	FLD_ThangThienKhiCong: varbinary("FLD_ThangThienKhiCong", { length: 60 }),
	FLD_ThangThienVoCong: varbinary("FLD_ThangThienVoCong", { length: 144 }),
	FLD_ThangThienLichLuyen: int("FLD_ThangThienLichLuyen"),
	FLD_ThangThienVoCongDiemSo: int("FLD_ThangThienVoCongDiemSo"),
	FLD_ADD_HP: int("FLD_ADD_HP").notNull(),
	FLD_ADD_AT: varchar("FLD_ADD_AT", { length: 50 }),
	FLD_ADD_DF: varchar("FLD_ADD_DF", { length: 50 }),
	FLD_ADD_HB: int("FLD_ADD_HB").notNull(),
	FLD_ADD_MP: int("FLD_ADD_MP").notNull(),
	FLD_ADD_MZ: int("FLD_ADD_MZ").notNull(),
	FLD_ZS: int("FLD_ZS").notNull(),
	FLD_VIPDJ: bigint("FLD_VIPDJ", { mode: "number" }).notNull(),
	FLD_FQID: varchar("FLD_FQID", { length: 20 }),
	SoLanGietNguoi: bigint("SoLanGietNguoi", { mode: "number" }),
	BiGietSoLan: bigint("BiGietSoLan", { mode: "number" }),
	FLD_SuPhu: varbinary("FLD_SuPhu", { length: 28 }),
	FLD_DeTu: varbinary("FLD_DeTu", { length: 60 }),
	FLD_SuDoVoCong: varbinary("FLD_SuDoVoCong", { length: 10 }),
	FLD_GiaiTruThoiGian: varchar("FLD_GiaiTruThoiGian", { length: 50 }),
	FLD_TitlePoints: int("FLD_TitlePoints"),
	CongThanhChienThoiGian: datetime("CongThanhChienThoiGian", { mode: 'string'}),
	FLD_XB: int("FLD_XB"),
	FLD_RoseTitlePoints: int("FLD_RoseTitlePoints"),
	FLD_SpeakingType: int("FLD_SpeakingType"),
	FLD_NSZITEM: varbinary("FLD_NSZITEM", { length: 600 }),
	FLD_LJKONGFU: varbinary("FLD_LJKONGFU", { length: 128 }),
	FLD_STIME: varbinary("FLD_STIME", { length: 320 }),
	BangPhai_DoCongHien: int("BangPhai_DoCongHien"),
	FLD_MLZ: int("FLD_MLZ"),
	FLD_PVP_Piont: int("FLD_PVP_Piont"),
	FLD_ThanNuVoCongDiemSo: int("FLD_ThanNuVoCongDiemSo"),
	FLD_LOVE_WORD: varchar("FLD_LOVE_WORD", { length: 50 }),
	FLD_MARITAL_STATUS: int("FLD_MARITAL_STATUS"),
	FLD_MARRIED: int("FLD_MARRIED"),
	FLD_JH_DATE: datetime("FLD_JH_DATE", { mode: 'string'}),
	FLD_FB_TIME: int("FLD_FB_TIME"),
	FLD_LOST_WX: int("FLD_LOST_WX"),
	FLD_GET_WX: int("FLD_GET_WX"),
	FLD_HD_TIME: int("FLD_HD_TIME"),
	FLD_KieuToc: varbinary("FLD_KieuToc", { length: 4 }),
	FLD_KhuonMat: varbinary("FLD_KhuonMat", { length: 4 }),
	FLD_WHTB: int("FLD_WHTB"),
	FLD_CHTIME: varchar("FLD_CHTIME", { length: 500 }),
	FLD_CONFIG: varchar("FLD_CONFIG", { length: 100 }),
	FLD_FASHION_ITEM: varbinary("FLD_FASHION_ITEM", { length: 5082 }),
	FLD_QUEST_FINISH: varbinary("FLD_QUEST_FINISH", { length: 1000 }),
	FLD_ADD_CLVC: int("FLD_ADD_CLVC"),
	FLD_ADD_PTVC: int("FLD_ADD_PTVC"),
	FLD_ADD_KC: int("FLD_ADD_KC"),
	FLD_CHECK_GIFTCODE: varchar("FLD_CHECK_GIFTCODE", { length: 100 }),
	FLD_Free_Spin: int("FLD_Free_Spin").notNull(),
	FLD_Member_VIP: int("FLD_Member_VIP").notNull(),
	FLD_VIP_Point: int("FLD_VIP_Point").notNull(),
	FLD_ActionInDay: longtext("FLD_ActionInDay").notNull(),
	FLD_CheckInCode: longtext("FLD_CheckInCode").notNull(),
	FLD_BuyEventShop: int("FLD_BuyEventShop").notNull(),
	FLD_BuyEventShopTime: datetime("FLD_BuyEventShopTime", { mode: 'string'}).notNull(),
	FLD_CTIME_STR: longtext("FLD_CTIME_STR").notNull(),
	FLD_WorldBoss_Point: int("FLD_WorldBoss_Point").notNull(),
	FLD_PkPoint: int("FLD_PkPoint").notNull(),
	FLD_SafePoint: int("FLD_SafePoint").notNull(),
	FLD_ThemWuxun_MoiNgay: int("FLD_ThemWuxun_MoiNgay").notNull(),
	FLD_GiamWuxun_MoiNgay: int("FLD_GiamWuxun_MoiNgay").notNull(),
	FLD_NhiemVuDaTauID: int("FLD_NhiemVuDaTauID").notNull(),
	FLD_NhiemVuDaTauLevel: int("FLD_NhiemVuDaTauLevel").notNull(),
	FLD_ActionInWeek: longtext("FLD_ActionInWeek").notNull(),
	FLD_PHTD_DiemSo: int("FLD_PHTD_DiemSo").notNull(),
	FLD_KyGui_Gold: bigint("FLD_KyGui_Gold", { mode: "number" }).notNull(),
	FLD_KyGui_Cash: int("FLD_KyGui_Cash").notNull(),
	FLD_DiemHoangKim: int("FLD_DiemHoangKim").notNull(),
	FLD_ITEM_STR: text("FLD_ITEM_STR"),
	FLD_WEARITEM_STR: text("FLD_WEARITEM_STR"),
},
(table) => {
	return {
		FLD_NAME: unique("FLD_NAME").on(table.FLD_NAME),
	}
});

export const EventTop = mysqlTable("EventTop", {
	id: int("id").autoincrement().notNull(),
	TenNhanVat: varchar("TenNhanVat", { length: 50 }),
	BangPhai: varchar("BangPhai", { length: 50 }),
	TheLuc: varchar("TheLuc", { length: 50 }),
	DangCap: int("DangCap"),
	GietNguoiSoLuong: int("GietNguoiSoLuong"),
	TuVongSoLuong: int("TuVongSoLuong"),
	PhanKhuTinTuc: varchar("PhanKhuTinTuc", { length: 50 }),
	NpcDiemSo: int("NpcDiemSo").notNull(),
	TotalDiemSo: int("TotalDiemSo").notNull(),
});

export const ForceWar_Rewards_Request = mysqlTable("ForceWar_Rewards_Request", {
	ID: int("ID").autoincrement().notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_Name: varchar("FLD_Name", { length: 50 }),
	FLD_Reward_Name: varchar("FLD_Reward_Name", { length: 100 }),
	FLD_Gold: bigint("FLD_Gold", { mode: "number" }).notNull(),
	FLD_VoHoang: int("FLD_VoHoang").notNull(),
	FLD_VoHuan: int("FLD_VoHuan").notNull(),
	FLD_Status: int("FLD_Status").notNull(),
	FLD_Cash: int("FLD_Cash").notNull(),
	FLD_Item: varchar("FLD_Item", { length: 500 }),
	FLD_Time_Request: datetime("FLD_Time_Request", { mode: 'string'}).notNull(),
	FLD_Time_Added: datetime("FLD_Time_Added", { mode: 'string'}).notNull(),
});

export const ItemRecord = mysqlTable("ItemRecord", {
	ID: int("ID").autoincrement().notNull(),
	UserId: varchar("UserId", { length: 50 }),
	UserName: varchar("UserName", { length: 50 }),
	ToUserId: varchar("ToUserId", { length: 50 }),
	ToUserName: varchar("ToUserName", { length: 50 }),
	Global_ID: varchar("Global_ID", { length: 50 }),
	VatPham_ID: varchar("VatPham_ID", { length: 50 }),
	VatPhamTen: varchar("VatPhamTen", { length: 50 }),
	VatPhamSoLuong: int("VatPhamSoLuong"),
	VatPhamThuocTinh: varchar("VatPhamThuocTinh", { length: 100 }),
	SoTien: int("SoTien"),
	LoaiHinh: varchar("LoaiHinh", { length: 50 }),
	ThoiGian: datetime("ThoiGian", { mode: 'string'}),
});

export const ITEMSELL = mysqlTable("ITEMSELL", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE"),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_RETURN: int("FLD_RETURN"),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon"),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon"),
	FLD_TienHoa: int("FLD_TienHoa"),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai"),
	FLD_DAYS: int("FLD_DAYS"),
});

export const LoginRecord = mysqlTable("LoginRecord", {
	ID: int("ID").autoincrement().notNull(),
	UserId: varchar("UserId", { length: 50 }),
	UserName: varchar("UserName", { length: 50 }),
	UserIp: varchar("UserIp", { length: 50 }),
	LoaiHinh: varchar("LoaiHinh", { length: 50 }),
	ThoiGian: datetime("ThoiGian", { mode: 'string'}),
});

export const LogPK = mysqlTable("LogPK", {
	ID: int("ID").autoincrement().notNull(),
	Nguoigiet: varchar("Nguoigiet", { length: 50 }),
	Nguoibigiet: varchar("Nguoibigiet", { length: 50 }),
	Thoigian: datetime("Thoigian", { mode: 'string'}),
});

export const Log_DeleteItem = mysqlTable("Log_DeleteItem", {
	ID: int("ID").autoincrement().notNull(),
	MaItem: int("MaItem").notNull(),
	IDItem: int("IDItem").notNull(),
	Thoigian: datetime("Thoigian", { mode: 'string'}).notNull(),
	LevelItem: varchar("LevelItem", { length: 50 }),
	Username: varchar("Username", { length: 50 }),
	TrangThai: int("TrangThai").notNull(),
});

export const ShopEvent = mysqlTable("ShopEvent", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE"),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_RETURN: int("FLD_RETURN"),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon"),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon"),
	FLD_TienHoa: int("FLD_TienHoa"),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai"),
	FLD_DAYS: int("FLD_DAYS"),
});

export const ShopHoangKim = mysqlTable("ShopHoangKim", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE").notNull(),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE").notNull(),
	FLD_RETURN: int("FLD_RETURN").notNull(),
	FLD_NUMBER: int("FLD_NUMBER").notNull(),
	FLD_MAGIC1: int("FLD_MAGIC1").notNull(),
	FLD_MAGIC2: int("FLD_MAGIC2").notNull(),
	FLD_MAGIC3: int("FLD_MAGIC3").notNull(),
	FLD_MAGIC4: int("FLD_MAGIC4").notNull(),
	FLD_MAGIC5: int("FLD_MAGIC5").notNull(),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon").notNull(),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon").notNull(),
	FLD_TienHoa: int("FLD_TienHoa").notNull(),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai").notNull(),
	FLD_DAYS: int("FLD_DAYS").notNull(),
	FLD_GuildLevel: int("FLD_GuildLevel").notNull(),
});

export const ShopVoHoang = mysqlTable("ShopVoHoang", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE"),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_RETURN: int("FLD_RETURN"),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon"),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon"),
	FLD_TienHoa: int("FLD_TienHoa"),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai"),
	FLD_DAYS: int("FLD_DAYS"),
});

export const ShopVoHuan = mysqlTable("ShopVoHuan", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE"),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_RETURN: int("FLD_RETURN"),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon"),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon"),
	FLD_TienHoa: int("FLD_TienHoa"),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai"),
	FLD_DAYS: int("FLD_DAYS"),
});

export const ShopWorldBoss = mysqlTable("ShopWorldBoss", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 255 }),
	FLD_PRICE: int("FLD_PRICE"),
	FLD_DESC: varchar("FLD_DESC", { length: 1000 }),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_RETURN: int("FLD_RETURN"),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon"),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon"),
	FLD_TienHoa: int("FLD_TienHoa"),
	FLD_PhaiChangKhoaLai: int("FLD_PhaiChangKhoaLai"),
	FLD_DAYS: int("FLD_DAYS"),
});

export const TBL_ACCOUNT = mysqlTable("TBL_ACCOUNT", {
	ID: int("ID").notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }).notNull(),
	FLD_PASSWORD: varchar("FLD_PASSWORD", { length: 50 }).notNull(),
	FLD_CARD: varchar("FLD_CARD", { length: 50 }),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_QU: varchar("FLD_QU", { length: 50 }),
	FLD_ANSWER: varchar("FLD_ANSWER", { length: 50 }),
	FLD_REGIP: varchar("FLD_REGIP", { length: 50 }),
	FLD_REGTIME: datetime("FLD_REGTIME", { mode: 'string'}),
	FLD_LASTLOGINTIME: timestamp("FLD_LASTLOGINTIME", { mode: 'string' }),
	FLD_LASTLOGINIP: varchar("FLD_LASTLOGINIP", { length: 50 }),
	FLD_VIP: int("FLD_VIP").default(0),
	FLD_ZT: int("FLD_ZT").default(0),
	FLD_ONLINE: int("FLD_ONLINE").default(0),
	FLD_SEX: int("FLD_SEX").default(0),
	FLD_RXPIONT: int("FLD_RXPIONT").default(0).notNull(),
	FLD_RXPIONTX: int("FLD_RXPIONTX").default(0).notNull(),
	FLD_VIPTIM: timestamp("FLD_VIPTIM", { mode: 'string' }),
	FLD_Mail: varchar("FLD_Mail", { length: 50 }),
	FLD_FQ: varchar("FLD_FQ", { length: 50 }),
	FLD_JF: int("FLD_JF"),
	FLD_ZJF: int("FLD_ZJF"),
	FLD_YY: varchar("FLD_YY", { length: 50 }),
	FLD_BD: int("FLD_BD"),
	FLD_PAY: int("FLD_PAY"),
	FLD_INCOME: int("FLD_INCOME"),
	FLD_CARDOLD: varchar("FLD_CARDOLD", { length: 50 }),
	FLD_MONEY: int("FLD_MONEY"),
	FLD_TotalAmount: int("FLD_TotalAmount"),
	FLD_LOCK: int("FLD_LOCK"),
	FLD_SAFEWORD: varchar("FLD_SAFEWORD", { length: 50 }),
	FLD_SPREADERID: varchar("FLD_SPREADERID", { length: 50 }),
	FLD_SPREADER_LEVEL: int("FLD_SPREADER_LEVEL").notNull(),
	FLD_RUNMORE: timestamp("FLD_RUNMORE", { mode: 'string' }),
	FLD_MACHINEID: varchar("FLD_MACHINEID", { length: 50 }),
	FLD_COIN: int("FLD_COIN"),
	FLD_TRANSFER_TIMES: int("FLD_TRANSFER_TIMES").notNull(),
	FLD_USERID: int("FLD_USERID"),
	FLD_QCVIP: int("FLD_QCVIP"),
	FLD_QCVIPTIM: timestamp("FLD_QCVIPTIM", { mode: 'string' }),
	FLD_WCVIP: int("FLD_WCVIP"),
	FLD_WCVIPTIM: timestamp("FLD_WCVIPTIM", { mode: 'string' }),
	FLD_QDCS: int("FLD_QDCS"),
	FLD_QDSJ: timestamp("FLD_QDSJ", { mode: 'string' }),
	// Warning: Can't parse bit(1) from database
	// bit(1)Type: bit(1)("FLD_CHECKLOGIN"),
	FLD_CHECKIP: varchar("FLD_CHECKIP", { length: 50 }),
	FLD_LANIP: varchar("FLD_LANIP", { length: 50 }),
	FLD_TYPE: int("FLD_TYPE").default(0).notNull(),
	FLD_GIFTPOINT: int("FLD_GIFTPOINT").default(0).notNull(),
	FLD_PHONE: int("FLD_PHONE").default(0).notNull(),
},
(table) => {
	return {
		FLD_ID: unique("FLD_ID").on(table.FLD_ID),
	}
});

export const TBL_AscQigongOption = mysqlTable("TBL_AscQigongOption", {
	ID: int("ID").autoincrement().notNull(),
	FLD_PID: int("FLD_PID"),
	FLD_INDEX: int("FLD_INDEX"),
	FLD_JOB: int("FLD_JOB"),
	FLD_NAME: text("FLD_NAME"),
	FLD_DES: varchar("FLD_DES", { length: 2000 }),
	FLD_ChiSo1: float("FLD_ChiSo1"),
	FLD_Bonus1: float("FLD_Bonus1").notNull(),
	FLD_ChuThich1: varchar("FLD_ChuThich1", { length: 500 }),
	FLD_ChiSo2: float("FLD_ChiSo2").notNull(),
	FLD_Bonus2: float("FLD_Bonus2").notNull(),
	FLD_ChuThich2: varchar("FLD_ChuThich2", { length: 500 }),
	FLD_Hieuqua1: float("FLD_Hieuqua1").notNull(),
	FLD_ChuThich3: varchar("FLD_ChuThich3", { length: 500 }),
	FLD_Hieuqua2: float("FLD_Hieuqua2").notNull(),
	FLD_ChuThich4: varchar("FLD_ChuThich4", { length: 500 }),
});

export const TBL_BuffOfGuild = mysqlTable("TBL_BuffOfGuild", {
	ID: int("ID").autoincrement().notNull(),
	Guild_Level: int("Guild_Level").notNull(),
	Bonus_HP: int("Bonus_HP").notNull(),
	Bonus_MP: int("Bonus_MP").notNull(),
	Bonus_ATK: int("Bonus_ATK").notNull(),
	Bonus_DF: int("Bonus_DF").notNull(),
	Bonus_Percent_ATKSkill: int("Bonus_Percent_ATKSkill").notNull(),
	Bonus_DefSkill: int("Bonus_DefSkill").notNull(),
	Bonus_Abilities: int("Bonus_Abilities").notNull(),
	Bonus_Percent_Exp: int("Bonus_Percent_Exp").notNull(),
	Bonus_Percent_Lucky: int("Bonus_Percent_Lucky").notNull(),
	Bonus_Percent_Drop: int("Bonus_Percent_Drop").notNull(),
	Bonus_Percent_DropGold: int("Bonus_Percent_DropGold").notNull(),
});

export const TBL_Buff_TanThu = mysqlTable("TBL_Buff_TanThu", {
	Id: int("Id").autoincrement().notNull(),
	Buff_Name: varchar("Buff_Name", { length: 500 }),
	Buff_Level: int("Buff_Level").notNull(),
	Buff_LevelX: int("Buff_LevelX").notNull(),
	Buff_TrungSinh: int("Buff_TrungSinh").notNull(),
	Buff_Exp: int("Buff_Exp").notNull(),
	Buff_ItemID: int("Buff_ItemID").notNull(),
});

export const TBL_CheckIn = mysqlTable("TBL_CheckIn", {
	Id: int("Id").autoincrement().notNull(),
	FLD_Item: varchar("FLD_Item", { length: 50 }),
	FLD_Item_Name: varchar("FLD_Item_Name", { length: 100 }),
	FLD_ItemVIP: varchar("FLD_ItemVIP", { length: 50 }),
	FLD_ItemVIP_Name: varchar("FLD_ItemVIP_Name", { length: 100 }),
	FLD_Time: timestamp("FLD_Time", { mode: 'string' }).notNull(),
	FLD_CheckCode: varchar("FLD_CheckCode", { length: 50 }),
	FLD_CheckCodeVIP: varchar("FLD_CheckCodeVIP", { length: 50 }),
});

export const TBL_DropOptions = mysqlTable("TBL_DropOptions", {
	ID: int("ID").autoincrement().notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 200 }),
	FLD_LEVEL1: int("FLD_LEVEL1").notNull(),
	FLD_LEVEL2: int("FLD_LEVEL2").notNull(),
	FLD_RATE: int("FLD_RATE").notNull(),
	FLD_OPTION: int("FLD_OPTION").notNull(),
	FLD_TYPE: int("FLD_TYPE").notNull(),
	FLD_Drop: int("FLD_Drop").notNull(),
	FLD_OpenBox: int("FLD_OpenBox").notNull(),
	FLD_ShopNPC: int("FLD_ShopNPC").notNull(),
	FLD_WebShop: int("FLD_WebShop").notNull(),
});

export const TBL_GIFTCODE = mysqlTable("TBL_GIFTCODE", {
	Id: int("Id").autoincrement().notNull(),
	GiftCode: varchar("GiftCode", { length: 50 }),
	Reward_Type: int("Reward_Type").notNull(),
	Use_Times: int("Use_Times").notNull(),
	UserID: varchar("UserID", { length: 50 }),
	OneTimePerUserName: int("OneTimePerUserName").notNull(),
});

export const TBL_GIFTCODE_REWARDS = mysqlTable("TBL_GIFTCODE_REWARDS", {
	ID: int("ID").autoincrement().notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_TYPE: int("FLD_TYPE").notNull(),
	FLD_GOLD: bigint("FLD_GOLD", { mode: "number" }).notNull(),
	FLD_WUXUN: int("FLD_WUXUN").notNull(),
	FLD_VOHOANG: int("FLD_VOHOANG").notNull(),
	FLD_CASH: int("FLD_CASH").notNull(),
	FLD_ITEM: varchar("FLD_ITEM", { length: 500 }),
});

export const TBL_Guild_SupportSettings = mysqlTable("TBL_Guild_SupportSettings", {
	ID: int("ID").autoincrement().notNull(),
	FLD_MaKichHoat: varchar("FLD_MaKichHoat", { length: 50 }),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_Name: varchar("FLD_Name", { length: 50 }),
	FLD_Description: varchar("FLD_Description", { length: 500 }),
	FLD_PointRequest: int("FLD_PointRequest").notNull(),
	FLD_Guild_Level: int("FLD_Guild_Level").notNull(),
	FLD_Buff_DropGold: float("FLD_Buff_DropGold").notNull(),
	FLD_Buff_DropExp: float("FLD_Buff_DropExp").notNull(),
	FLD_Buff_DropItem: float("FLD_Buff_DropItem").notNull(),
	FLD_Buff_Lucky: float("FLD_Buff_Lucky").notNull(),
	FLD_Buff_ATK: int("FLD_Buff_ATK").notNull(),
	FLD_Buff_DEF: int("FLD_Buff_DEF").notNull(),
	FLD_Buff_HP: int("FLD_Buff_HP").notNull(),
	FLD_Buff_Qigong: int("FLD_Buff_Qigong").notNull(),
	FLD_SummonBoss: int("FLD_SummonBoss").notNull(),
	FLD_Minutes: int("FLD_Minutes").notNull(),
	FLD_Type: int("FLD_Type").notNull(),
	FLD_Level: int("FLD_Level").notNull(),
});

export const TBL_HatchItem = mysqlTable("TBL_HatchItem", {
	ID: int("ID").autoincrement().notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 200 }),
	FLD_PIDX: int("FLD_PIDX").notNull(),
	FLD_NAMEX: varchar("FLD_NAMEX", { length: 200 }),
	FLD_Number: int("FLD_Number").notNull(),
	FLD_PP: int("FLD_PP").notNull(),
	FLD_MAGIC0: int("FLD_MAGIC0").notNull(),
	FLD_MAGIC1: int("FLD_MAGIC1").notNull(),
	FLD_MAGIC2: int("FLD_MAGIC2").notNull(),
	FLD_MAGIC3: int("FLD_MAGIC3").notNull(),
	FLD_MAGIC4: int("FLD_MAGIC4").notNull(),
	FLD_LowSoul: int("FLD_LowSoul").notNull(),
	FLD_MedSoul: int("FLD_MedSoul").notNull(),
	FLD_Quality: int("FLD_Quality").notNull(),
	FLD_Lock: int("FLD_Lock").notNull(),
	FLD_ExpiryDate: int("FLD_ExpiryDate").notNull(),
	FLD_Announce: int("FLD_Announce").notNull(),
});

export const TBL_HISTORY_SPIN = mysqlTable("TBL_HISTORY_SPIN", {
	ID: int("ID").autoincrement().notNull(),
	FLD_CHAR_NAME: varchar("FLD_CHAR_NAME", { length: 50 }),
	FLD_ITEM_ID: bigint("FLD_ITEM_ID", { mode: "number" }),
	FLD_SPIN_ID: int("FLD_SPIN_ID").notNull(),
	FLD_SPIN_TYPE: int("FLD_SPIN_TYPE"),
	FLD_SPIN: int("FLD_SPIN"),
	FLD_SPINX: int("FLD_SPINX"),
	FLD_ENERGY: int("FLD_ENERGY"),
	FLD_ENERGYX: int("FLD_ENERGYX"),
	FLD_TIME: datetime("FLD_TIME", { mode: 'string'}),
	FLD_STATUS: int("FLD_STATUS").notNull(),
	FLD_SPIN_RATE: int("FLD_SPIN_RATE").notNull(),
});

export const TBL_ItemOption = mysqlTable("TBL_ItemOption", {
	ID: int("ID").autoincrement().notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 100 }),
	Bonus_HP: int("Bonus_HP").notNull(),
	Bonus_PercentHP: int("Bonus_PercentHP"),
	Bonus_MP: int("Bonus_MP").notNull(),
	Bonus_PercentMP: int("Bonus_PercentMP"),
	Bonus_ATK: int("Bonus_ATK").notNull(),
	Bonus_PercentATK: int("Bonus_PercentATK").notNull(),
	Bonus_PercentDF: int("Bonus_PercentDF"),
	Bonus_DF: int("Bonus_DF").notNull(),
	Bonus_PercentATKSkill: int("Bonus_PercentATKSkill"),
	Bonus_DefSkill: int("Bonus_DefSkill"),
	Bonus_Qigong: int("Bonus_Qigong").notNull(),
	Bonus_DropGold: int("Bonus_DropGold").notNull(),
	Bonus_Exp: int("Bonus_Exp").notNull(),
	Bonus_Lucky: int("Bonus_Lucky").notNull(),
	Bonus_Accuracy: int("Bonus_Accuracy").notNull(),
	Bonus_Evasion: int("Bonus_Evasion").notNull(),
	Bonus_DiemHoangKim: int("Bonus_DiemHoangKim").notNull(),
});

export const TBL_KyGuiVatPham = mysqlTable("TBL_KyGuiVatPham", {
	id: int("id").autoincrement().notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_ItemName: varchar("FLD_ItemName", { length: 50 }),
	FLD_ItemPID: int("FLD_ItemPID").notNull(),
	FLD_ItemOption: varchar("FLD_ItemOption", { length: 500 }),
	FLD_Amount: int("FLD_Amount").notNull(),
	FLD_Price: bigint("FLD_Price", { mode: "number" }).notNull(),
	FLD_Type: int("FLD_Type").notNull(),
	FLD_Time: timestamp("FLD_Time", { mode: 'string' }).notNull(),
	FLD_STATUS: int("FLD_STATUS").notNull(),
	FLD_RESIDE2: int("FLD_RESIDE2").notNull(),
	FLD_LEVEL: int("FLD_LEVEL").notNull(),
	FLD_NOTICE: varchar("FLD_NOTICE", { length: 50 }),
	FLD_ITEMBYTE: varbinary("FLD_ITEMBYTE", { length: 73 }),
});

export const TBL_ListMagicQigong = mysqlTable("TBL_ListMagicQigong", {
	ID: int("ID").notNull(),
	FLD_MAGIC: int("FLD_MAGIC").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 100 }),
	Shop_PP: int("Shop_PP").notNull(),
	Drop_PP: int("Drop_PP").notNull(),
	QigongID: int("QigongID").notNull(),
	DungChung_QigongID: varchar("DungChung_QigongID", { length: 500 }),
	DonVi: int("DonVi").notNull(),
},
(table) => {
	return {
		QigongID: unique("QigongID").on(table.QigongID),
	}
});

export const TBL_OPEN_CHEST = mysqlTable("TBL_OPEN_CHEST", {
	ID: int("ID").autoincrement().notNull(),
	CHEST_NAME: varchar("CHEST_NAME", { length: 200 }),
	CHEST_ID: int("CHEST_ID").notNull(),
	ITEM_NAME: varchar("ITEM_NAME", { length: 300 }),
	FLD_ITEM: varchar("FLD_ITEM", { length: 250 }),
	FLD_LEVEL: varchar("FLD_LEVEL", { length: 50 }),
	FLD_JOB_LEVEL: int("FLD_JOB_LEVEL").notNull(),
	FLD_JOB: varchar("FLD_JOB", { length: 50 }),
	FLD_GENDER: int("FLD_GENDER").notNull(),
	FLD_FORCE: int("FLD_FORCE").notNull(),
	FLD_PP: int("FLD_PP").notNull(),
});

export const TBL_QigongOption = mysqlTable("TBL_QigongOption", {
	ID: int("ID").autoincrement().notNull(),
	FLD_PID: int("FLD_PID"),
	FLD_INDEX: int("FLD_INDEX"),
	FLD_JOB: int("FLD_JOB"),
	FLD_NAME: text("FLD_NAME"),
	FLD_DES: varchar("FLD_DES", { length: 2000 }),
	FLD_ChiSo1: float("FLD_ChiSo1"),
	FLD_Bonus1: float("FLD_Bonus1").notNull(),
	FLD_ChuThich1: varchar("FLD_ChuThich1", { length: 500 }),
	FLD_ChiSo2: float("FLD_ChiSo2").notNull(),
	FLD_Bonus2: float("FLD_Bonus2").notNull(),
	FLD_ChuThich2: varchar("FLD_ChuThich2", { length: 500 }),
	FLD_Hieuqua1: float("FLD_Hieuqua1").notNull(),
	FLD_ChuThich3: varchar("FLD_ChuThich3", { length: 500 }),
	FLD_Hieuqua2: float("FLD_Hieuqua2").notNull(),
	FLD_ChuThich4: varchar("FLD_ChuThich4", { length: 500 }),
});

export const TBL_RebornSettings = mysqlTable("TBL_RebornSettings", {
	ID: int("ID").autoincrement().notNull(),
	Reborn_Times: int("Reborn_Times").notNull(),
	Reborn_Level: int("Reborn_Level").notNull(),
	Reborn_Level_Down: int("Reborn_Level_Down").notNull(),
	Item_Request: varchar("Item_Request", { length: 500 }),
	Bonus_HP: int("Bonus_HP").notNull(),
	Bonus_ATK: int("Bonus_ATK").notNull(),
	Bonus_DF: int("Bonus_DF").notNull(),
	Bonus_WX: int("Bonus_WX").notNull(),
	Bonus_Gold: int("Bonus_Gold").notNull(),
	Bonus_Cash: int("Bonus_Cash").notNull(),
	Bonus_VoHoang: int("Bonus_VoHoang").notNull(),
	Item_Rewards: varchar("Item_Rewards", { length: 500 }),
});

export const TBL_SPIN = mysqlTable("TBL_SPIN", {
	ID: int("ID").autoincrement().notNull(),
	FLD_ID: int("FLD_ID").notNull(),
	FLD_ITEM_NAME: varchar("FLD_ITEM_NAME", { length: 50 }),
	FLD_PP1: int("FLD_PP1").notNull(),
	FLD_PP2: int("FLD_PP2").notNull(),
	FLD_INFO: text("FLD_INFO"),
	FLD_SHOW: varchar("FLD_SHOW", { length: 50 }),
	FLD_SPIN_TYPE: int("FLD_SPIN_TYPE").notNull(),
	FLD_ITEM_TYPE: int("FLD_ITEM_TYPE").notNull(),
	FLD_MAGIC0_MIN: int("FLD_MAGIC0_MIN").notNull(),
	FLD_MAGIC0_MAX: int("FLD_MAGIC0_MAX").notNull(),
});

export const TBL_StoreOnline = mysqlTable("TBL_StoreOnline", {
	ID: int("ID").autoincrement().notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_ITEM: varbinary("FLD_ITEM", { length: 8000 }),
	FLD_ITEM_STR: longtext("FLD_ITEM_STR"),
});

export const TBL_SuDoSoLieu = mysqlTable("TBL_SuDoSoLieu", {
	ID: int("ID").autoincrement().notNull(),
	FLD_TNAME: varchar("FLD_TNAME", { length: 50 }),
	FLD_INDEX: int("FLD_INDEX"),
	FLD_SNAME: varchar("FLD_SNAME", { length: 50 }),
	FLD_TLEVEL: int("FLD_TLEVEL"),
	FLD_STLEVEL: int("FLD_STLEVEL").notNull(),
	FLD_STYHD: int("FLD_STYHD").notNull(),
	FLD_STWG1: int("FLD_STWG1").notNull(),
	FLD_STWG2: int("FLD_STWG2").notNull(),
	FLD_STWG3: int("FLD_STWG3").notNull(),
});

export const TBL_TayLuyenVatPham_ThuocTinh = mysqlTable("TBL_TayLuyenVatPham_ThuocTinh", {
	Id: int("Id").autoincrement().notNull(),
	FLD_Name: varchar("FLD_Name", { length: 100 }),
	FLD_Option: int("FLD_Option").notNull(),
	FLD_Line: int("FLD_Line").notNull(),
	FLD_PP: int("FLD_PP").notNull(),
	FLD_NguyenLieuID: int("FLD_NguyenLieuID").notNull(),
	FLD_TayLuyen_Type: int("FLD_TayLuyen_Type").notNull(),
});

export const TBL_ThienPhu = mysqlTable("TBL_ThienPhu", {
	ID: int("ID").autoincrement().notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_TP_CongLuc_LV: int("FLD_TP_CongLuc_LV").notNull(),
	FLD_TP_PhongNgu_LV: int("FLD_TP_PhongNgu_LV").notNull(),
	FLD_TP_CLVC_LV: int("FLD_TP_CLVC_LV").notNull(),
	FLD_TP_ULPT_LV: int("FLD_TP_ULPT_LV").notNull(),
	FLD_TP_SinhMenh_LV: int("FLD_TP_SinhMenh_LV").notNull(),
	FLD_TP_NoiCong_LV: int("FLD_TP_NoiCong_LV").notNull(),
	FLD_TP_NeTranh_LV: int("FLD_TP_NeTranh_LV").notNull(),
	FLD_TP_ChinhXac_LV: int("FLD_TP_ChinhXac_LV").notNull(),
});

export const TBL_XWWL_DROP = mysqlTable("TBL_XWWL_DROP", {
	id: int("id").autoincrement().notNull(),
	FLD_LEVEL1: int("FLD_LEVEL1"),
	FLD_LEVEL2: int("FLD_LEVEL2").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_PP: int("FLD_PP").notNull(),
	FLD_MAGIC0: int("FLD_MAGIC0").notNull(),
	FLD_MAGIC1: int("FLD_MAGIC1").notNull(),
	FLD_MAGIC2: int("FLD_MAGIC2").notNull(),
	FLD_MAGIC3: int("FLD_MAGIC3").notNull(),
	FLD_MAGIC4: int("FLD_MAGIC4").notNull(),
	FLD_SoCapPhuHon: int("FLD_SoCapPhuHon").notNull(),
	FLD_TrungCapPhuHon: int("FLD_TrungCapPhuHon").notNull(),
	FLD_TienHoa: int("FLD_TienHoa").notNull(),
	FLD_KhoaLai: int("FLD_KhoaLai").notNull(),
	FLD_SUNX: varchar("FLD_SUNX", { length: 500 }),
	CoMoThongBao: int("CoMoThongBao"),
	FLD_TYPE: int("FLD_TYPE").notNull(),
});

export const TBL_XWWL_Guild = mysqlTable("TBL_XWWL_Guild", {
	ID: int("ID").notNull(),
	G_Name: varchar("G_Name", { length: 50 }),
	G_Master: varchar("G_Master", { length: 50 }),
	G_Notice: varchar("G_Notice", { length: 60 }),
	Leve: int("Leve"),
	ThanhDanh: int("ThanhDanh"),
	MonHuy: varbinary("MonHuy", { length: 800 }),
	MonPhucWord: int("MonPhucWord"),
	MonPhucMauSac: int("MonPhucMauSac"),
	BangPhaiVoHuan: int("BangPhaiVoHuan"),
	Thang: int("Thang"),
	Thua: int("Thua"),
	Hoa: int("Hoa"),
	MonPhaiTaiSan: varchar("MonPhaiTaiSan", { length: 50 }),
	BangPhaiCongHien: int("BangPhaiCongHien").notNull(),
	BangPhaiTaiNguyen: int("BangPhaiTaiNguyen").notNull(),
	BangPhaiTroCap: varchar("BangPhaiTroCap", { length: 500 }),
	KichHoatPhoBan: int("KichHoatPhoBan").notNull(),
});

export const TBL_XWWL_GuildMember = mysqlTable("TBL_XWWL_GuildMember", {
	ID: int("ID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	G_Name: varchar("G_Name", { length: 50 }),
	Leve: int("Leve"),
	FLD_LEVEL: int("FLD_LEVEL"),
	FLD_JoinTime: timestamp("FLD_JoinTime", { mode: 'string' }).notNull(),
	FLD_LastDonateTime: timestamp("FLD_LastDonateTime", { mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	FLD_Donate: int("FLD_Donate").notNull(),
});

export const TBL_XWWL_ITEM = mysqlTable("TBL_XWWL_ITEM", {
	FLD_PID: int("FLD_PID").autoincrement().notNull(),
	FLD_TayLuyen_Type: int("FLD_TayLuyen_Type").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 200 }),
	FLD_ITEMGROUP: varchar("FLD_ITEMGROUP", { length: 50 }),
	FLD_RESIDE1: int("FLD_RESIDE1").notNull(),
	FLD_RESIDE2: int("FLD_RESIDE2").notNull(),
	FLD_SEX: int("FLD_SEX").notNull(),
	FLD_LEVEL: int("FLD_LEVEL").notNull(),
	FLD_UP_LEVEL: int("FLD_UP_LEVEL").notNull(),
	FLD_RECYCLE_MONEY: int("FLD_RECYCLE_MONEY").notNull(),
	FLD_SALE_MONEY: int("FLD_SALE_MONEY").notNull(),
	FLD_QUESTITEM: int("FLD_QUESTITEM").notNull(),
	FLD_NJ: int("FLD_NJ").notNull(),
	FLD_DF: int("FLD_DF").notNull(),
	FLD_AT1: int("FLD_AT1").notNull(),
	FLD_AT2: int("FLD_AT2").notNull(),
	FLD_AP: int("FLD_AP").notNull(),
	FLD_JOB_LEVEL: int("FLD_JOB_LEVEL").notNull(),
	FLD_ZX: int("FLD_ZX").notNull(),
	FLD_EL: int("FLD_EL").notNull(),
	FLD_WX: int("FLD_WX").notNull(),
	FLD_WXJD: int("FLD_WXJD").notNull(),
	FLD_MONEY: int("FLD_MONEY").notNull(),
	FLD_WEIGHT: int("FLD_WEIGHT").notNull(),
	FLD_TYPE: int("FLD_TYPE").notNull(),
	FLD_NEED_MONEY: int("FLD_NEED_MONEY").notNull(),
	FLD_NEED_FIGHTEXP: int("FLD_NEED_FIGHTEXP").notNull(),
	FLD_MAGIC1: int("FLD_MAGIC1").notNull(),
	FLD_MAGIC2: int("FLD_MAGIC2").notNull(),
	FLD_MAGIC3: int("FLD_MAGIC3").notNull(),
	FLD_MAGIC4: int("FLD_MAGIC4").notNull(),
	FLD_MAGIC5: int("FLD_MAGIC5").notNull(),
	FLD_SIDE: int("FLD_SIDE").notNull(),
	FLD_SELL_TYPE: int("FLD_SELL_TYPE").notNull(),
	FLD_LOCK: int("FLD_LOCK").notNull(),
	FLD_SERIES: int("FLD_SERIES").notNull(),
	FLD_INTEGRATION: int("FLD_INTEGRATION").notNull(),
	FLD_DES: varchar("FLD_DES", { length: 2000 }),
	FLD_HEAD_WEAR: int("FLD_HEAD_WEAR").notNull(),
	FLD_SHIELD: int("FLD_SHIELD").notNull(),
	FLD_CJL: int("FLD_CJL").notNull(),
	FLD_CHAN: int("FLD_CHAN").notNull(),
	FLD_BS: int("FLD_BS").notNull(),
	FLD_PetNameType: int("FLD_PetNameType").notNull(),
});

export const TBL_XWWL_KONGFU = mysqlTable("TBL_XWWL_KONGFU", {
	FLD_PID: int("FLD_PID").autoincrement().notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_SOURCE_AT: int("FLD_SOURCE_AT").notNull(),
	FLD_AT: int("FLD_AT"),
	FLD_MP: int("FLD_MP"),
	FLD_LEVEL: int("FLD_LEVEL"),
	FLD_NEEDEXP: int("FLD_NEEDEXP"),
	FLD_JOB: int("FLD_JOB"),
	FLD_ZX: int("FLD_ZX"),
	FLD_JOBLEVEL: int("FLD_JOBLEVEL"),
	FLD_TYPE: int("FLD_TYPE"),
	FLD_EFFERT: int("FLD_EFFERT"),
	FLD_INDEX: int("FLD_INDEX"),
	FLD_CongKichSoLuong: int("FLD_CongKichSoLuong"),
	FLD_VoCongLoaiHinh: int("FLD_VoCongLoaiHinh"),
	FLD_MoiCapNguyHai: varchar("FLD_MoiCapNguyHai", { length: 50 }),
	FLD_MoiCapThemNguyHai: int("FLD_MoiCapThemNguyHai"),
	FLD_MoiCapThemMP: int("FLD_MoiCapThemMP"),
	FLD_MoiCapThemLichLuyen: int("FLD_MoiCapThemLichLuyen"),
	FLD_MoiCapThemTuLuyenDangCap: int("FLD_MoiCapThemTuLuyenDangCap"),
	FLD_MoiCapVoCongDiemSo: int("FLD_MoiCapVoCongDiemSo"),
	FLD_VoCongToiCaoDangCap: int("FLD_VoCongToiCaoDangCap"),
	FLD_TIME: int("FLD_TIME"),
	FLD_DEATHTIME: int("FLD_DEATHTIME"),
	FLD_CDTIME: int("FLD_CDTIME"),
	Time_Animation: int("Time_Animation").notNull(),
});

export const TBL_XWWL_MAP = mysqlTable("TBL_XWWL_MAP", {
	FLD_MID: int("FLD_MID").autoincrement().notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_FILE: varchar("FLD_FILE", { length: 50 }),
	X: float("X"),
	Y: float("Y"),
});

export const TBL_XWWL_MONSTER = mysqlTable("TBL_XWWL_MONSTER", {
	FLD_PID: int("FLD_PID").notNull(),
	FLD_NAME: varchar("FLD_NAME", { length: 200 }),
	FLD_LEVEL: int("FLD_LEVEL").notNull(),
	FLD_HP: int("FLD_HP").notNull(),
	FLD_AT: int("FLD_AT").notNull(),
	FLD_DF: int("FLD_DF").notNull(),
	FLD_EXP: int("FLD_EXP").notNull(),
	FLD_BOSS: int("FLD_BOSS").notNull(),
	FLD_AUTO: int("FLD_AUTO").notNull(),
	FLD_NPC: int("FLD_NPC").notNull(),
	FLD_QUEST: int("FLD_QUEST").notNull(),
	FLD_QUESTID: int("FLD_QUESTID").notNull(),
	FLD_STAGES: int("FLD_STAGES").notNull(),
	FLD_QUESTITEM: int("FLD_QUESTITEM").notNull(),
	FLD_PP: int("FLD_PP").notNull(),
	FLD_GOLD: int("FLD_GOLD").notNull(),
	FLD_Accuracy: int("FLD_Accuracy").notNull(),
	FLD_Evasion: int("FLD_Evasion").notNull(),
	FLD_FreeDrop: int("FLD_FreeDrop").notNull(),
},
(table) => {
	return {
		FLD_PID: unique("FLD_PID").on(table.FLD_PID),
	}
});

export const TBL_XWWL_NPC = mysqlTable("TBL_XWWL_NPC", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID"),
	FLD_X: float("FLD_X"),
	FLD_Z: float("FLD_Z"),
	FLD_Y: float("FLD_Y"),
	FLD_FACE0: float("FLD_FACE0"),
	FLD_FACE: float("FLD_FACE"),
	FLD_MID: int("FLD_MID"),
	FLD_NAME: varchar("FLD_NAME", { length: 200 }),
	FLD_HP: bigint("FLD_HP", { mode: "number" }),
	FLD_AT: bigint("FLD_AT", { mode: "number" }),
	FLD_DF: bigint("FLD_DF", { mode: "number" }),
	FLD_NPC: int("FLD_NPC"),
	FLD_NEWTIME: int("FLD_NEWTIME"),
	FLD_LEVEL: int("FLD_LEVEL"),
	FLD_EXP: int("FLD_EXP"),
	FLD_AUTO: int("FLD_AUTO").notNull(),
	FLD_BOSS: int("FLD_BOSS").notNull(),
	FLD_GOLD: int("FLD_GOLD").notNull(),
	FLD_Accuracy: int("FLD_Accuracy").notNull(),
	FLD_Evasion: int("FLD_Evasion").notNull(),
	FLD_QItemDrop: int("FLD_QItemDrop").notNull(),
	FLD_QDropPP: int("FLD_QDropPP").notNull(),
	FLD_FreeDrop: int("FLD_FreeDrop").notNull(),
});

export const TBL_XWWL_OPEN = mysqlTable("TBL_XWWL_OPEN", {
	ID: int("ID").notNull(),
	FLD_PID: int("FLD_PID").notNull(),
	FLD_PIDX: int("FLD_PIDX").notNull(),
	FLD_NUMBER: int("FLD_NUMBER"),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_NAMEX: varchar("FLD_NAMEX", { length: 50 }),
	FLD_PP: int("FLD_PP").notNull(),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_MAGIC5: int("FLD_MAGIC5"),
	FLD_FJ_ThucTinh: int("FLD_FJ_ThucTinh"),
	FLD_FJ_TienHoa: int("FLD_FJ_TienHoa"),
	FLD_FJ_TrungCapPhuHon: int("FLD_FJ_TrungCapPhuHon"),
	FLD_BD: int("FLD_BD"),
	FLD_DAYS: int("FLD_DAYS"),
	CoMoThongBao: int("CoMoThongBao"),
	FLD_RandomOption: int("FLD_RandomOption").notNull(),
});

export const TBL_XWWL_PublicWarehouse = mysqlTable("TBL_XWWL_PublicWarehouse", {
	ID: int("ID").notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_MONEY: varchar("FLD_MONEY", { length: 50 }),
	FLD_ITEM: varbinary("FLD_ITEM", { length: 4380 }),
	FLD_ITIME: varbinary("FLD_ITIME", { length: 50 }),
	FLD_ZBVER: int("FLD_ZBVER"),
});

export const TBL_XWWL_SELL = mysqlTable("TBL_XWWL_SELL", {
	ID: int("ID").notNull(),
	FLD_NPCNAME: varchar("FLD_NPCNAME", { length: 50 }),
	FLD_NID: bigint("FLD_NID", { mode: "number" }),
	FLD_INDEX: int("FLD_INDEX"),
	FLD_PID: bigint("FLD_PID", { mode: "number" }),
	FLD_ITEMNAME: varchar("FLD_ITEMNAME", { length: 100 }),
	FLD_MONEY: bigint("FLD_MONEY", { mode: "number" }),
	FLD_SELL: bigint("FLD_SELL", { mode: "number" }).notNull(),
	FLD_MAGIC0: int("FLD_MAGIC0"),
	FLD_MAGIC1: int("FLD_MAGIC1"),
	FLD_MAGIC2: int("FLD_MAGIC2"),
	FLD_MAGIC3: int("FLD_MAGIC3"),
	FLD_MAGIC4: int("FLD_MAGIC4"),
	FLD_CanVoHuan: int("FLD_CanVoHuan"),
});

export const TBL_XWWL_Warehouse = mysqlTable("TBL_XWWL_Warehouse", {
	ID: int("ID").notNull(),
	FLD_ID: varchar("FLD_ID", { length: 50 }),
	FLD_NAME: varchar("FLD_NAME", { length: 50 }),
	FLD_MONEY: varchar("FLD_MONEY", { length: 50 }),
	FLD_ITEM: varbinary("FLD_ITEM", { length: 4380 }),
});